// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxajwbhmgrqdollvsxyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4YWp3YmhtZ3JxZG9sbHZzeHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzkzMDEsImV4cCI6MjA2MTI1NTMwMX0.H1iNcy0WBdC50EVa7yxltw5Nq4SYlseUktq7e7wwZiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);